Add an option to save the output to a different folder from 'save_dir'.
AI-sandbox/neural-admixture pull request #11
Opened 2022-03-23 18:31 UTC by gil-i

Modified parse_infer_args to add the option '--out_dir' for the path to store the output, inference.py was modified accordingly to use this variable as output directory.
If '--out_dir' is not given this variable sets to '--save_dir' which is a required argument.

2022-03-23 18:43 UTC, gil-i commented
Hello @AlbertDominguez I have a use case where I want to run neural admixture multiple times but I want to store the output in different folders with the same name, this is why I want to have an option to directly store the output in the folder I want to, to avoid possible overwrites when running multiple processes of neural admixture at the same time. 

Not really sure if the way I set the default value of out_dir to save_dir was the standard way to do it but it should work.

Thanks in advance.

2022-03-24 09:35 UTC, AlbertDominguez approved these changes

2022-03-24 09:35 UTC, AlbertDominguez commented on neural_admixture/src/utils.py
> +    parser.add_argumnet('--out_dir', required=False, type=str, help='Path to save the output. If not given sets to --save_dir.')
```suggestion
    parser.add_argument('--out_dir', required=False, type=str, help='Path to save the output. If not given sets to --save_dir.')
```

2022-03-24 09:41 UTC, AlbertDominguez requested changes
Hi @gil-i , thanks for the request. While you added the argument, it would be unused as it is as the file _neural_admixture/src/inference.py_ in has not been updated to use this new argument. Could you update it also, please?

2025-02-28 08:53 UTC, closed without merging